### ISSUE TITLE
Setting integrality / binary undefined in managed SCIP mode

### ISSUE THREAD

**Issue by matbesancon** [SCIP-Interfaces/SCIP.jl#116]
The MOI wrapper is directly defining:
`function MOI.add_constraint(o::Optimizer, func::SVF, set::S) where {S <: VAR_TYPES}`
using the low-level SCIP generated API, we should have an intermediate function in `managed_scip.jl`

**Comment by leethargo** [comment]
I kind of agree, in terms of consistency, but there are two special properties for these "variable" constraints (bounds and integral types):
- they are not considered constraints by SCIP (with their own `SCIP_CONS`), so they do not need reference counting for memory management (in the scope of ManagedSCIP).
- there is some not-so-nice setting of implicit bounds of `[0, 1]` for binary variables, together with storing and resetting older bounds. Would we have to handle this logic twice, at the ManagedSCIP and also at the MOI level?

**Comment by matbesancon** [comment]
Yes the idea was moving all parts requiring the Clang-generated API to managed, so that the dependency on the generated part is only in there (keeping it consistent with the other constraints).

Yes I saw the bounds, I think this could be handled once at the `ManagedSCIP` level, and only passed and not stored at MOI level

**Comment by leethargo** [comment]
OK, I'm open to that kind of change in this case.

But I wonder whether it makes sense to *require* a layer between all calls from the MOI interface implementation to the Clang wrapper, in general. For example, a lot of result queries (in #115) are just one-liners.

I also expect power users to make some direct calls to (currently) unwrapped calls. It is already relatively convenient to do so, as `SCIP.Optimizer` and `ManagedSCIP` are automatically `cconvert`ed to `Ptr{SCIP_}`.

**Comment by matbesancon** [comment]
Indeed this is maybe a pointless layer. I was thinking about it because the `managed` tests still required low-level manipulations as:
```
        # indicator constraint: z = 1 ==> 𝟙^T [x, y] <= 1.
        z = SCIP.add_variable(mscip)
        SCIP.@SC SCIP.SCIPchgVarType(mscip, SCIP.var(mscip, z), SCIP.SCIP_VARTYPE_BINARY, Ref{SCIP.SCIP_Bool}())
        SCIP.@SC SCIP.SCIPchgVarLb(mscip, SCIP.var(mscip, z), 0.0)
        SCIP.@SC SCIP.SCIPchgVarUb(mscip, SCIP.var(mscip, z), 1.0)

```
