### ISSUE TITLE
Building SCIP does not locate dylib although SCIPOPTDIR is set

### ISSUE THREAD

**Issue by jeremyomer** [SCIP-Interfaces/SCIP.jl#142]
Hello, I am using MacOs 10.12 and I just installed SCIP from scip.zib.de using  SCIPOptSuite-6.0.1-Darwin.sh file. I also properly set the SCIPOPTDIR environment to point to the install directory. I encountered the same very weird issue when trying to build SCIP.jl with Julia 1.1 and 1.2. In both cases I get the same error:

```
(v1.1) pkg> build SCIP
  Building SCIP → ~/.julia/packages/SCIP/IJWEZ/deps/build.log
┌ Error: Error building `SCIP`:
│ ERROR: LoadError: Unable to locate SCIP installation.
│ Tried:
│ 	/Users/jeremy/Applications/SCIPOptSuite-6.0.1-Darwin/bin/libscip.dylib
│ 	/Users/jeremy/Applications/SCIPOptSuite-6.0.1-Darwin/lib/libscip.dylib
│ 	libscip.dylib
│ Note that this must be downloaded separately from scip.zib.de.
```

But, the required library is present at one of the tried location:
```
[jeremy ~/Applications ] ls /Users/jeremy/Applications/SCIPOptSuite-6.0.1-Darwin/lib/
cmake                 libgcg.3.0.dylib      libscip.6.0.1.0.dylib libscip.dylib         libsoplex.a           libzimpl.a
libgcg.3.0.1.0.dylib  libgcg.dylib          libscip.6.0.dylib     libsoplex-pic.a       libzimpl-pic.a
```
I'd really appreciate help to start using SCIP in my research. Thanks

**Comment by rschwarz** [comment]
I don't have a machine with OS X available, so I can't really help with that, sorry.

The error message does look familiar though. I think we had the same issue when we tried to use precompiled binaries for Travis CI. That's why SCIP is still [compiled](https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/.travis.yml#L32) on Travis for OS X.

Maybe it's a file permissions problem, or something like that?

**Comment by rschwarz** [comment]
I get the same error when using the precompiled OS X in Travis (see #143).

Maybe you can try compiling SCIP from source? This works in Travis.

**Comment by jeremyomer** [comment]
Thank you for the answer ! 

Indeed, it worked by compiling SCIP from source with CMAKE. I'm closing the issue since another one was open on the subject.
