### ISSUE TITLE
Update to CEnum@0.2.0

### ISSUE THREAD

**Issue by metab0t** [SCIP-Interfaces/SCIP.jl#150]
Is dependency on `CEnum@^0.1.0` necessary?

**Comment by rschwarz** [comment]
Yes. It fails with newer versions, see also #144 

This has to do with the version of `Clang.jl` used to generate the C wrapper.
One could regenerate the C wrapper from the SCIP header files with a newer version of `Clang` and then also use a more recent version of `CEnum`. See #77.
