### ISSUE TITLE
SCIP is currently not suported on NT

### ISSUE THREAD

**Issue by 121180875** [SCIP-Interfaces/SCIP.jl#151]
Building SCIP ────────────→→ `C:\Users\qiuchongrong\.juliapro\JuliaPro_v1.3.1
-2\packages\SCIP\lczBF\deps\build.log`
┌┌ Error: Error building `SCIP`:
││ ERROR: LoadError: SCIP is currently not supported on "NT"
││ Stacktrace:
││  [1] error(::String) at .\error.jl:33
││  [2] top-level scope at C:\Users\qiuchongrong\.juliapro\JuliaPro_v1.3.1-2\pac
kages\SCIP\lczBF\deps\build.jl:19
││  [3] include at .\boot.jl:328 [inlined]
││  [4] include_relative(::Module, ::String) at .\loading.jl:1105
││  [5] include(::Module, ::String) at .\Base.jl:31
││  [6] include(::String) at .\client.jl:424
││  [7] top-level scope at none:5
││ in expression starting at C:\Users\qiuchongrong\.juliapro\JuliaPro_v1.3.1-2\p
ackages\SCIP\lczBF\deps\build.jl:14
└└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.3.1\share\julia\stdlib\
v1.3\Pkg\src\Operations.jl:898

**Comment by rschwarz** [comment]
Could you give some more context? E.g. what operating system are you using?
Does `NT` refer to some variant of Windows?

We do [support all operating systems](https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/deps/build.jl#L20) that we can cover by the available CI tools, including Windows, so I don't know why it's failing in your case.

**Comment by 121180875** [comment]
> Could you give some more context? E.g. what operating system are you using?
> Does `NT` refer to some variant of Windows?
> 
> We do [support all operating systems](https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/deps/build.jl#L20) that we can cover by the available CI tools, including Windows, so I don't know why it's failing in your case.

My operating system is Windows.I don't know what "NT" means.

**Comment by rschwarz** [comment]
Could you try the following commands for comparison:

```julia
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIALANG_HOME = /home/rs/opt/julia

julia> Sys.iswindows()
false

julia> Sys.KERNEL
:Linux
```

**Comment by 121180875** [comment]
> Could you try the following commands for comparison:
> 
> ```julia
> julia> versioninfo()
> Julia Version 1.4.0
> Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
> Platform Info:
>   OS: Linux (x86_64-pc-linux-gnu)
>   CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
> Environment:
>   JULIALANG_HOME = /home/rs/opt/julia
> 
> julia> Sys.iswindows()
> false
> 
> julia> Sys.KERNEL
> :Linux
> ```

julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_DEPOT_PATH = C:\Users\qiuchongrong\.juliapro\JuliaPro_v1.3.1-2;D:\JuliaP
ro\Julia-1.3.1\local\share\julia;D:\JuliaPro\Julia-1.3.1\share\julia
  JULIA_PKG_SERVER = pkg.juliacomputing.com

julia> Sys.iswindows()
true

julia> Sys.KERNEL
:NT

**Comment by rschwarz** [comment]
Thanks. If `Sys.iswindows()` is true, then I don't know why the build script is failing.
Are you possibly using a very old version of SCIP.jl?

**Comment by 121180875** [comment]
> Thanks. If `Sys.iswindows()` is true, then I don't know why the build script is failing.
> Are you possibly using a very old version of SCIP.jl?
Can you send me the code for the Settings you made when compiling the SCIP package?
Does SCIP need a specific version? Mine is SCIP V0.7.4.
System kernel display is NT, is it a problem of system kernel?

**Comment by rschwarz** [comment]
> Can you send me the code for the Settings you made when compiling the SCIP package?

I would recommend pre-built binaries.

For SCIP.jl, you need at least 0.8 for Windows support, but I recommend the latest (0.9.4) so that SCIP 7.0 is supported.

**Comment by 121180875** [comment]
> > Can you send me the code for the Settings you made when compiling the SCIP package?
> 
> I would recommend pre-built binaries.
> 
> For SCIP.jl, you need at least 0.8 for Windows support, but I recommend the latest (0.9.4) so that SCIP 7.0 is supported.
Hello.I have installed SCIP on my computer. I have installed the latest version of scip.jl.
I compiled scip.jl without setting the environment variables, and it worked.
Would you like to ask if this is OK?

**Comment by rschwarz** [comment]
> and it worked.

I'm not sure what you're saying. If it (now) worked for you, then all is good, right?
Above, you said that:

> Does SCIP need a specific version? Mine is SCIP V0.7.4.

I guess you mean the version of SCIP.jl. In that case, that version is too old an does not support Windows.

**Comment by 121180875** [comment]
> > and it worked.
> 
> I'm not sure what you're saying. If it (now) worked for you, then all is good, right?
> Above, you said that:
> 
> > Does SCIP need a specific version? Mine is SCIP V0.7.4.
> 
> I guess you mean the version of SCIP.jl. In that case, that version is too old an does not support Windows.
Sorry, I can't express it clearly, but it should be ready to use.Do you recommend some reference material about how to use SCIP in Julia?Because，I use SCIP first time.

**Comment by rschwarz** [comment]
I don't know what to add to the [instructions in the README](https://github.com/SCIP-Interfaces/SCIP.jl#getting-started)

**Comment by Jovansam** [comment]
I wonder whether this issues was ever resolved as I get the same problem:
>Building SCIP → `C:\Users\KitchenComputer\.julia\packages\SCIP\lczBF\deps\build.log`
┌ Error: Error building `SCIP`: 
│ ERROR: LoadError: SCIP is currently not supported on "NT"
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\KitchenComputer\.julia\packages\SCIP\lczBF\deps\build.jl:19
│  [3] include(::String) at .\client.jl:439
│  [4] top-level scope at none:5
│ in expression starting at C:\Users\KitchenComputer\.julia\packages\SCIP\lczBF\deps\build.jl:14
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892

I have SCIP installed. My machine details:
>julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
>
>julia> Sys.iswindows()
true
>
>julia> Sys.KERNEL
:NT
