### ISSUE TITLE
Formulation of Nonlinear Optimization with JuMP/Ipopt

### ISSUE THREAD

**Issue by ChrisNabold** [SCIP-Interfaces/SCIP.jl#155]
I try to solve the following problem:
using JuMP, Ipopt
 
m = Model(Ipopt.Optimizer)
 
function g(x,y)   # this function ecavuates the lowest eigenfrequency
A = [4.0*(x^4 + y^4), 2.0*y^4, 2.0*y^4, 4.0*y^4];
B = [4.0*(x^2 + y^2), -3.0*y^2, -3.0*y^2, 4.0*y^2];
A = reshape(A,2,2);
B = reshape(B,2,2);
eigv,dum = eig(A,B);
eVal = eigv[1];
return eVal
end
 
@variable(m, x, start = 1.0)
@variable(m, y, start = 1.0)
 
# I try to optimize the eigenfrequency such that x^2 + y^2 is at a minimum 
# how can I formulate this problem with JuMP?
 
@variable(m, eVal)
@NLexpression(m, eVal, g(x,y))
@variable(m, eVal == my_expr)
@NLconstraint(m, my_constr, my_expr >= 0.4)
@NLobjective(m, Min, x^2 + y^2)
optimize!(m)
println("x = ", value.(x), " y = ", value.(y))
 
Any help would be appreciated

**Comment by rschwarz** [comment]
SCIP only supports nonlinear functions given as expressions, so you can't use `eigv` or other Julia functions here.

It might be better to ask on [Discourse](https://discourse.julialang.org/c/domain/opt/13).
