### ISSUE TITLE
SCIP Dual Status

### ISSUE THREAD

**Issue by ccoffrin** [SCIP-Interfaces/SCIP.jl#157]
I got a report that SCIP.jl does not support the solution `dual_status` parameter.  I believe this parameter should be set to `NO_SOLUTION` if it is not available.

https://github.com/lanl-ansi/InfrastructureModels.jl/issues/68

CC @mlubin, @odow, @rb004f

**Comment by odow** [comment]
I can fix this. It's just:
```Julia
function MOI.get(::Optimizer, ::MOI.DualStatus)
    return MOI.NO_SOLUTION
end
```

**Comment by ccoffrin** [comment]
Thanks!
