### ISSUE TITLE
Increase CEnum versions

### ISSUE THREAD

**Issue by dourouc05** [SCIP-Interfaces/SCIP.jl#168]
I'm trying to install CUDA.jl with SCIP.jl already installed. I'm having troubles due to SCIP.jl only supporting CEnum.jl 0.1, while the current version is 0.4.1. CUDA.jl requires at least CEnum.jl 0.2 (which has been release roughly one year ago). It looks like updating to CEnum.jl 0.2 requires to rewrite all `@cenum` calls, though…

**Comment by rschwarz** [comment]
Yes, this is a known problem (#154) and would entail regenerating the wrappers.
