### ISSUE TITLE
ERROR: LoadError: SCIP is currently not supported on "NT"

### ISSUE THREAD

**Issue by litingjunlyn** [SCIP-Interfaces/SCIP.jl#169]
I want to install SCIP，but when I build SCIP,It haves error.
(@v1.4) pkg> build SCIP
   Building SCIP → `C:\Users\litingjun\.julia\packages\SCIP\lczBF\deps\build.log`
┌ Error: Error building `SCIP`:
│ ERROR: LoadError: SCIP is currently not supported on "NT"
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\litingjun\.julia\packages\SCIP\lczBF\deps\build.jl:19
│  [3] include(::String) at .\client.jl:439
│  [4] top-level scope at none:5
│ in expression starting at C:\Users\litingjun\.julia\packages\SCIP\lczBF\deps\build.jl:14
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:899

**Comment by rschwarz** [comment]
You likely have an old version of SCIP.jl installed (e.g. `0.7.4`), which did not support Windows yet, see #154. 
This is probably due to a version conflict with the dependency `CEnum`, see #77.
