### ISSUE TITLE
implement getsolvetime

### ISSUE THREAD

**Issue by mlubin** [SCIP-Interfaces/SCIP.jl#17]
So I'm starting to run some experiments using SCIP, and I'm going to begin complaining about the missing methods that I need to get things working. First one is ``getsolvetime``.

**Comment by leethargo** [comment]
I'm wondering now whether these kinds of methods need to be added to CSIP, which would require more releases and version updates every time.

CSIP also allows to access the internal `SCIP*` directly and with Julia's `ccall` we could then use all functions that don't require any special objects (such as `SCIP_VAR*` or `SCIP_CONS*`) currently hidden from the user.

Maybe this functionality could also be wrapped in a macro.
