### ISSUE TITLE
Copy CEnum as submodule to prevent downgrading of other packages

### ISSUE THREAD

**Issue by GregPlowman** [SCIP-Interfaces/SCIP.jl#174]
I understand `SCIP` is not compatible with the latest `CEnum.jl`, and this is a known, outstanding issue.

Would it be feasible and would there be interest in copying the old required `CEnum` into the `SCIP` package as a submodule, and removing the dependency on the external `CEnum` package? (It seems this would be an easy change?)

Then the latest `SCIP` can co-exist with the latest `Clp`, `Cbc` in the same environment.

**Comment by rschwarz** [comment]
Yes, I think this is feasible. Actually, in earlier versions of `Clang.jl`, a local `CEnum` module was created as part of the wrapper generation process, so there is precedent for it.

**Comment by rschwarz** [comment]
fixed by #175
