### ISSUE TITLE
Installation of SCIP 0.0.5 does no longer work.

### ISSUE THREAD

**Issue by ChrisNabold** [SCIP-Interfaces/SCIP.jl#176]

**Comment by ChrisNabold** [comment]
I tried to install SCIP 0.9.5 with the latest Julia 1.5. However the installation no longer works. It used to work with Scip 7.0 and Julia 1.4.2. The interface also does not work with SCIP 7.0.1.
Any help?
Thank you
Chris

**Comment by rschwarz** [comment]
It's difficult to say without more details of your problem, but it's true that SCIP.jl 0.9.5 was not compatible with SCIP 7.0.1, due to an explicit version check.

This check was now relaxed, and SCIP.jl 0.9.6 should work with SCIP 7.0.1.
