### ISSUE TITLE
are the install instructions for linux only?

### ISSUE THREAD

**Issue by mlubin** [SCIP-Interfaces/SCIP.jl#21]
If so, should mention explicitly.

**Comment by leethargo** [comment]
I don't even know, maybe it works for OS X, too.

**Comment by mlubin** [comment]
Let's say it's untested on OS X then

**Comment by jac0320** [comment]
Got this message when building in macOS. Pretty sure SCIP is installed. Be able to see CSIP in julia deps/usr/... But it doesn't go through when building.

INFO: Building SCIP
INFO: Attempting to Create directory /Users/jac0320/.julia/v0.4/SCIP/deps/downloads
INFO: Directory /Users/jac0320/.julia/v0.4/SCIP/deps/downloads already created
INFO: Downloading file https://github.com/SCIP-Interfaces/CSIP/archive/v0.3.5.zip
INFO: Done downloading file https://github.com/SCIP-Interfaces/CSIP/archive/v0.3.5.zip
INFO: Attempting to Create directory /Users/jac0320/.julia/v0.4/SCIP/deps/src
INFO: Directory /Users/jac0320/.julia/v0.4/SCIP/deps/src already created
INFO: Attempting to Create directory /Users/jac0320/.julia/v0.4/SCIP/deps
INFO: Directory /Users/jac0320/.julia/v0.4/SCIP/deps already created
INFO: Path /Users/jac0320/.julia/v0.4/SCIP/deps/src/CSIP-0.3.5 already created
INFO: Changing Directory to /Users/jac0320/.julia/v0.4/SCIP/deps/src/CSIP-0.3.5
make: Nothing to be done for `all'.
INFO: Changing Directory to /Users/jac0320/.julia/v0.4/SCIP/deps/src/CSIP-0.3.5
INFO: Changing Directory to /Users/jac0320/.julia/v0.4/SCIP/deps/src/CSIP-0.3.5
================================[ ERROR: SCIP ]=================================

LoadError: Provider BinDeps.BuildProcess failed to satisfy dependency libcsip
while loading /Users/jac0320/.julia/v0.4/SCIP/deps/build.jl, in expression starting on line 34

================================================================================

===========================================================[ BUILD ERRORS ]===========================================================

WARNING: SCIP had build errors.

 - packages with build errors remain installed in /Users/jac0320/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("SCIP")`
 - build a single package by running its `deps/build.jl` script

======================================================================================================================================

**Comment by jac0320** [comment]
And also this...
julia> BinDeps.debug("SCIP")
INFO: Reading build script...
The package declares 1 dependencies.
 - Library "libcsip"
    - Providers:
      - Simple Build Process

Thanks

**Comment by leethargo** [comment]
I don't know anything about building on OSX, but I'm guessing that the file extension `.so` could be a problem. Should it be `dylib` or something?

**Comment by leethargo** [comment]
updated instructions with 9592057.
