### ISSUE TITLE
Remove CSIP dependency

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/SCIP.jl#28]
Now that we have a working version and a better understanding of both Julia and the conceptual gap between SCIP and MathProgBase, we could build a more direct wrapper, skipping CSIP entirely.

We could also (in the same step) provide a Julia wrapper for the "raw" SCIP function(alitie)s, on which the MPB interface implementation is based. This would enable users to easily use the more advanced features directly, that is, without need for `:ccall`. It is unclear to what extent the public functions of SCIP should be made available, since the large number of these suggests a semi-automatic way of generating the wrappers.

CC: @fserra

**Comment by fserra** [comment]
I like this idea a lot.

 How would you like to generate the wrapper? As we have seen, there are two tried approaches. One is using clang.jl and the other is using doxygen and go (i think): https://github.com/ryanjoneil/SCIP.jl

**Comment by leethargo** [comment]
I tried the clang way to generate the first version of the wrapper in SCIP.jl and it was painless for CSIP. But in this case, there were few fancy types involved.
