### ISSUE TITLE
Document SCIP.jl within the JuliaOpt homepage

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/SCIP.jl#29]
It's not currently listed in the table, or the overview figure.

**Comment by mlubin** [comment]
Just needs a PR at https://github.com/JuliaOpt/juliaopt.github.io. The overview figure is old though, not sure what exactly to do with it.

**Comment by leethargo** [comment]
I figured, but was busy now and wanted a reminder for later.
Manually adjusting the figure probably isn't worth it, but maybe it could be generated somehow using Plots.jl or Compose.jl...

**Comment by leethargo** [comment]
fixed with [PR #39](https://github.com/JuliaOpt/juliaopt.github.io/pull/39).
