### ISSUE TITLE
Can the installation be fully automated?

### ISSUE THREAD

**Issue by chkwon** [SCIP-Interfaces/SCIP.jl#41]
Can `build.jl` download and compile the SCIP source codes by itself without needing `SCIPOPTDIR`? Is there anything that prevent it? License issue, perhaps? I just doubt that normal Julia users will need SCIP codes and binaries outside Julia. If they need it, they will install it outside Julia, I guess. Just like Ipopt.

**Comment by mlubin** [comment]
No, it cannot. SCIP's license unfortunately does not permit automated installations.

**Comment by chkwon** [comment]
Thanks for the confirmation.

**Comment by mlubin** [comment]
Might be worth saying something in the README about this

**Comment by leethargo** [comment]
And I did in a1357b7.
