### ISSUE TITLE
CSIP 0.3.6 is much faster than CSIP 0.4.0?

### ISSUE THREAD

**Issue by YankaiCao** [SCIP-Interfaces/SCIP.jl#50]
Hi, 

I find a quite wield thing. If I change CSIP_VERSION from 0.4.0 to 0.3.6, SCIP is much faster. 
To do that I also need to change line 1484 in csip.c
from  SCIP_in_CSIP(SCIPtrySolFree(scip, &sol, FALSE,  TRUE, TRUE, TRUE, &stored));
to     SCIP_in_CSIP(SCIPtrySolFree(scip, &sol, FALSE, FALSE, TRUE, TRUE, TRUE, &stored));

However, after the change, csip.c in version 0.3.6 is almost the same as csip.c in 0.4.0.  But the performance is very different.  I guess the dependence of two versions are different. 

Here is test code

using JuMP, SCIP
function test(iter)
for i = 1:iter
    m= Model()
    nvar = 1000
    @variable(m, 0<=x[1:nvar]<=1)
    @constraint(m, con[i in 1:(nvar-2)], x[i]+x[i+1]<=1)
    @objective(m, :Min, sum{(x[i]+x[i+2])^2, i in 1:(nvar-2)})
    m.solver=SCIPSolver("display/verblevel", 0)
    solve(m)
end
end
test(10)

on my computer, version 0.3.6 takes 15seconds, while version 0.4.0 takes 80 seconds. This is not the old problem I tested, the difference in solution time can be even ten times for many problems I solved.

**Comment by leethargo** [comment]
Did you only change the version of CSIP, or also link to another version of SCIP?
CSIP up to 0.3.6 supports SCIP 3.2.1, but CSIP 0.4.0 supports SCIP 4.0.0. If you use the same SCIP, the behavior and result might be wrong. If you link different SCIP versions, the reason for differences in performance might lie there.

The change you point out is actually the only significant code change between CSIP 0.3.6 to 0.4.0 (see [ed4039ac](https://github.com/SCIP-Interfaces/CSIP/commit/ed4039ac238f6993ec2462a1862285fc5ba7997c)), so at this point I'm not sure what you are comparing.

**Comment by leethargo** [comment]
Most likely not related to SCIP.jl itself.
