### ISSUE TITLE
quadratic objective with @objective doesn't works

### ISSUE THREAD

**Issue by YankaiCao** [SCIP-Interfaces/SCIP.jl#51]
Hi,

I am solving QCQP. I find that if I model quadratic constraints and objective using @constraint and @objective, and then SCIP returns wrong answer. Instead, is I models using @NLconstraint and @NLobjective, SCIP gives the correct answer? Why is it?

**Comment by leethargo** [comment]
Can you please post your model and the output in each case?

Maybe it has to do with the optimization direction or some other sign-issue, that might be introduced in the reformulation of the `NLconstraint`.

**Comment by leethargo** [comment]
Not reproducible.
