### ISSUE TITLE
Quadratic constraint handler does not have LAPACK for eigenvalue computation.

### ISSUE THREAD

**Issue by michaellindon** [SCIP-Interfaces/SCIP.jl#61]
I compiled with `make SHARED=true ZLIB=false GMP=false READLINE=false LPSOPT=opt-gccold OPT=opt-gccold IPOPT=true scipoptlib`

drawing attention to IPOPT=true, yet one I try to solve my model within JuMP I get

"Quadratic constraint handler does not have LAPACK for eigenvalue computation. Will assume that matrices (with size > 2x2) are indefinite."

I thought the way to resolve this was to compile with IPOPT=true, but that is what I have done and still get this error.

**Comment by leethargo** [comment]
Hm, I also would have suggested to set `IPOPT=true`. What version of SCIP are you using?
Could you also compile SCIP (the binary) and run it to see the prompt? It should tell the versions of the linked libraries.

**Comment by michaellindon** [comment]
Thanks for the quick response, I ran the binary in `scipoptsuite-4.0.0/scip-4.0.0/bin` and it is quite revealing:

```
SCIP version 4.0.0 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 3.0.0] [GitHash: a80a247]
Copyright (C) 2002-2017 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)

External codes: 
  SoPlex 3.0.0         Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: b0cccbd]
  CppAD 20160000.1     Algorithmic Differentiation of C++ algorithms developed by B. Bell (www.coin-or.org/CppAD)

user parameter file <scip.set> not found - using default parameters
```

I'm guessing Ipopt should be visible here in the external codes right?

**Comment by michaellindon** [comment]
Sorry my bad, I confused myself and hadn't included IPOPT=true. I've been having so much trouble getting this to compile.

With 
`make ZLIB=false GMP=false READLINE=false LPSOPT=opt-gccold OPT=opt-gccold IPOPT=true SHARED=true scipoptlib`

I get an error
`build failed with GMP=false and LPS=spx2: use GMP=true or make sure that SoPlex is also built without GMP support (make GMP=false)`

**Comment by leethargo** [comment]
I guess this is unrelated to SCIP.jl then. Could you take this to the SCIP mailing list?

**Comment by michaellindon** [comment]
thanks, i will :)
