### ISSUE TITLE
SCIP fails in Julia/Atom for Windows

### ISSUE THREAD

**Issue by heliofuchigami** [SCIP-Interfaces/SCIP.jl#64]
Hi, 

I have installed the academic licence of SCIP but I had no success to use it in Julia/Atom in Windows OS.

I tried with AmplNLWriter, but even so nothing... It seems the binary scipampl is not supported in Windows...

The SCIPOptSuite 5.0.1 is supported on Julia 0.6.2.1 ?

Thanks in advance.

**Comment by leethargo** [comment]
Sorry, only Linux is supported now, see the [README](https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/README.md)
