### ISSUE TITLE
Error building SCIP

### ISSUE THREAD

**Issue by sharabhs** [SCIP-Interfaces/SCIP.jl#65]
INFO: Building SCIP
==============================================================[ ERROR: SCIP ]==============================================================
LoadError: None of the selected providers can install dependency libcsip.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\shara\.julia\v0.6\SCIP\deps\build.jl, in expression starting on line 52

===========================================================================================================================================
=============================================================[ BUILD ERRORS ]==============================================================
WARNING: SCIP had build errors.

 - packages with build errors remain installed in C:\Users\shara\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("SCIP")`
 - build a single package by running its `deps/build.jl` script

===========================================================================================================================================

**Comment by fserra** [comment]
I am sorry but we do not support windows

**Comment by sharabhs** [comment]
Any plans in future?

**Comment by fserra** [comment]
Not from my side and I am guessing @leethargo also doesn't have any plans. Also, I wouldn't know how to do it, so somebody would have to try to do it an open a PR
