### ISSUE TITLE
build.jl: automatically build CSIP

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/SCIP.jl#7]
Still need `scipoptsuite` dependency :disappointed:

Also, can we enforce a dependency on a specific version of CSIP?

**Comment by mlubin** [comment]
You could add a function to CSIP that returns an API version.

**Comment by leethargo** [comment]
Sure, that would help to check version correctness. I was thinking more in terms of downloading the right release from github. I guess that can actually be done quite easily via the download URL.

**Comment by mlubin** [comment]
Yep, download URL.

**Comment by mlubin** [comment]
For the purposes of development and testing, maybe we should set up an automatic SCIP install via Travis CI and not build.jl. At least we'd get unit tests running on each commit.

**Comment by leethargo** [comment]
Sure, that makes sense.

**Comment by mlubin** [comment]
I can try setting up travis. Could you flip it on for this repository?

**Comment by leethargo** [comment]
Cool, thanks. I enabled the repo for TravisCI with default settings.

Note that precompiled `libscipopt.so` files are currently not offered on the SCIP homepage :disappointed:

**Comment by mlubin** [comment]
@leethargo, do you know of a link we could use to directly download scipoptsuite-3.2.1.tgz?

**Comment by leethargo** [comment]
Have a look at the [package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=scipoptsuite) that exists for Arch Linux.

**Comment by leethargo** [comment]
This will be fixed with #13
